Artemis-Issue-Tracker/Models/Project.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations.Schema;

namespace Artemis_Issue_Tracker.Models
{
    public class Project
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string type { get; set; }
        public int progress { get; set; }
        public bool favorite { get; set; }
        public DateTime sprint_length { get; set; }
        public DateTime created { get; set; }

        // Navigation Properties
        public ICollection<Task>? tasks { get; set; }
        public ICollection<Sprint>? sprints { get; set; }

        public Project() 
        {
            name = string.Empty;
            description = string.Empty;
            type = string.Empty;
            progress = 0;
            favorite = false;
            sprint_length = DateTime.MinValue;
            created = DateTime.Now;
        } 
    }
}

Artemis-Issue-Tracker/ViewModels/ProjectViewModel.cs
using Artemis_Issue_Tracker.Models;
using X.PagedList;

namespace Artemis_Issue_Tracker
{
    public class ProjectViewModel
    {
        public IPagedList<Project> Projects { get; set; }
        public int Pages { get; set; }
        public int CurrentPage { get; set; }
    }
}

Artemis-Issue-Tracker/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Artemis_Issue_Tracker.Data;
using Artemis_Issue_Tracker.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Data;
using X.PagedList;
using System.Diagnostics;

namespace Artemis_Issue_Tracker.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private UserManager<IdentityUser> _userManager;

        public ProjectsController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Projects
        // This is where we need to filter the list of projects based on the UserProject table
        [Authorize]
        public async Task<IActionResult> Index(string sortOrder, string searchTerm, int? page)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["TitleSort"] = sortOrder == "title_ascend" ? "title_descend" : "title_ascend";
            ViewData["DateSort"] = String.IsNullOrEmpty(sortOrder) ? "date_descend" : "";

            var currentUserId = _userManager.GetUserId(User);
            var projects = from p in _context.Project
                           join up in _context.UserProject
                           on p.id equals up.project_id
                           where up.user_id == currentUserId
                           select p;

            if (!String.IsNullOrEmpty(searchTerm))
            {
                projects = projects.Where(p => p.name.Contains(searchTerm));
            }

            switch (sortOrder)
            {
                case "title_ascend":
                    projects = projects.OrderBy(p => p.name);
                    break;
                case "title_descend":
                    projects = projects.OrderByDescending(p => p.name);
                    break;
                case "date_descend":
                    projects = projects.OrderByDescending(p => p.created);
                    break;
                default:
                    projects = projects.OrderBy(p => p.created);
                    break;
            }

            int pageNumber = page ?? 1,
                pageSize = 8;

            // The ProjectViewModel at the moment is not neccessary atm
            // However, it may be useful in the future if I need to pass more than just the Project model info to the view
            var projectsViewModel = new ProjectViewModel
            {
                Projects = await projects.ToPagedListAsync(pageNumber, pageSize)
            };

            return View(projectsViewModel.Projects);
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Project == null)
            {
                return NotFound();
            }

            var project = await _context.Project
                .FirstOrDefaultAsync(m => m.id == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // GET: Projects/Create
        // responsible for giving us the project create view
        public IActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        // Once on the view this handles the routes that come next
        // Need to add the project id and user id to the UserProject table here 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,name,description,type,progress,favorite,sprint_length,created")] Project project)
        {
            if (ModelState.IsValid)
            {
                _context.Project.Add(project);
                await _context.SaveChangesAsync();

                var currentUserId = _userManager.GetUserId(User);
                var userProject = new UserProject() { user_id = currentUserId, project_id = project.id };

                _context.UserProject.Add(userProject);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Project == null)
            {
                return NotFound();
            }

            var project = await _context.Project.FindAsync(id);

            if (project == null)
            {
                return NotFound();
            }
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,name,description,type,progress,favorite,sprint_length,created")] Project project)
        {
            if (id != project.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                using (var transaction = _context.Database.BeginTransaction())
                {
                    try
                    {
                        _context.Update(project);

                        await _context.SaveChangesAsync();
                        await transaction.CommitAsync();

                        return RedirectToAction(nameof(Index));
                    }
                    catch (DBConcurrencyException ex) 
                    {
                        await transaction.RollbackAsync();
                        return StatusCode(500, $"An error occurred while updating the project: {ex.Message}");
                    }
                }
            }
            return View(project);
        }
        // GET: Projects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Project == null)
            {
                return NotFound();
            }

            var project = await _context.Project
                .FirstOrDefaultAsync(m => m.id == id);

            if (project == null)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var currentUserId = _userManager.GetUserId(User);

            using (var transaction = _context.Database.BeginTransaction())
            {
                try
                {
                    var project = await _context.Project.FindAsync(id);

                    if (project == null)
                    {
                        return NotFound();
                    }

                    var userProject = await _context.UserProject
                                            .Where(up => up.project_id == project.id && up.user_id == currentUserId)
                                            .SingleAsync();

                    if (userProject == null)
                    {
                        return NotFound();
                    }

                    _context.UserProject.Remove(userProject);
                    _context.Project.Remove(project);

                    // Save changes in a transaction
                    await _context.SaveChangesAsync();
                    await transaction.CommitAsync();

                    return RedirectToAction(nameof(Index));
                }
                catch (DBConcurrencyException ex)
                {
                    // If an error occurs, roll back the transaction
                    await transaction.RollbackAsync();
                    return StatusCode(500, $"An error occurred while deleting the project: {ex.Message}");
                }
            }
        }

        private bool ProjectExists(int id)
        {
          return _context.Project.Any(e => e.id == id);
        }
    }
}

Artemis-Issue-Tracker/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Artemis_Issue_Tracker.Data;
using Artemis_Issue_Tracker.Models;
using System.Data;

namespace Artemis_Issue_Tracker.Controllers
{
    public class TasksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TasksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Issues
        public async Task<IActionResult> Index()
        {
            List<Models.Task> tasks = await _context.Task.OrderBy(t => t.position).ToListAsync();

            foreach (Models.Task task in tasks)
            {
                task.sub_tasks = task.sub_tasks.OrderBy(st => st.position).ToList();
            }

            return View(tasks);
        }

        // GET: Issues/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Task == null)
            {
                return NotFound();
            }

            var issue = await _context.Task
                .FirstOrDefaultAsync(m => m.id == id);
            if (issue == null)
            {
                return NotFound();
            }

            return View(issue);
        }

        // GET: Issues/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Issues/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("name,project_id,parent_id,description,priority,status,type,position,progress,time_estimate,time_log,start,end,created")] Models.Task task)
        {
            if (ModelState.IsValid)
            {
                _context.Add(task);
                await _context.SaveChangesAsync();
                return Json(new { id = task.id, success = true });
            }

            var errors = ModelState.ToDictionary(x => x.Key, x => x.Value.Errors.Select(e => e.ErrorMessage));
            return Json(new { success = false, errors });
        }

        // GET: Issues/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Task == null)
            {
                return NotFound();
            }

            var issue = await _context.Task.FindAsync(id);
            if (issue == null)
            {
                return NotFound();
            }
            return View(issue);
        }

        // POST: Issues/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,AttachmentURL,CreationDate,SprintCount")] Models.Task issue)
        {
            if (id != issue.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(issue);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TaskExists(issue.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(issue);
        }

        [HttpPost]
        public async Task<IActionResult> UpdatePositions(int[] taskIds) 
        {
            using (var transaction = _context.Database.BeginTransaction())
            {
                try
                {
                    for (int i = 0; i < taskIds.Length; i++)
                    {
                        if (TaskExists(taskIds[i])) 
                        {
                            var taskId = taskIds[i];
                            var task = await _context.Task.FindAsync(taskId);
                            task.position = i;

                            _context.Update(task);
                        }
                    }

                    await _context.SaveChangesAsync();
                    await transaction.CommitAsync();

                    return Ok();
                }
                catch (DBConcurrencyException ex)
                {
                    await transaction.RollbackAsync();
                    return StatusCode(500, $"An error occurred while updating the position of the task: {ex.Message}");
                }
            }
        }

        // GET: Issues/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Task == null)
            {
                return NotFound();
            }

            var issue = await _context.Task
                .FirstOrDefaultAsync(m => m.id == id);
            if (issue == null)
            {
                return NotFound();
            }

            return View(issue);
        }

        // POST: Issues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Task == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Issue'  is null.");
            }
            var issue = await _context.Task.FindAsync(id);
            if (issue != null)
            {
                _context.Task.Remove(issue);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult GetCreateTaskModal()
        {
            var newTask = new Models.Task();
            return PartialView("Create", newTask);
        }

        private bool TaskExists(int id)
        {
          return _context.Task.Any(e => e.id == id);
        }
    }
}

Artemis-Issue-Tracker/Views/Projects/Create.cshtml
@model Artemis_Issue_Tracker.Models.Project

@{
    ViewData["Title"] = "Create";
}

<h1 class="text-light">Create</h1>

<h4 class="text-light">New Project</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="name" class="control-label text-light">Name</label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="description" class="control-label text-light">Description</label>
                <input asp-for="description" class="form-control" />
                <span asp-validation-for="description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="type" class="control-label text-light">Type</label>
                <input asp-for="type" class="form-control" />
                <span asp-validation-for="type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="progress" class="control-label text-light">Progress</label>
                <input asp-for="progress" class="form-control" />
                <span asp-validation-for="progress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="favorite" class="control-label text-light">Favorite</label>
                <input asp-for="favorite" class="form-control" />
                <span asp-validation-for="favorite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="sprint_length" class="control-label text-light">Sprint Length</label>
                <input asp-for="sprint_length" class="form-control" />
                <span asp-validation-for="sprint_length" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="created" class="control-label text-light">Creation Date</label>
                <input asp-for="created" class="form-control" />
                <span asp-validation-for="created" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="text-light" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Artemis-Issue-Tracker/Views/Projects/Delete.cshtml
@model Artemis_Issue_Tracker.Models.Project

@{
    ViewData["Title"] = "Delete";
}

<h1 class="text-light">Delete</h1>

<h3 class="text-light">Are you sure you want to delete this?</h3>
<div>
    <h4 class="text-light">Project</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            <label class="text-light">Name</label>
        </dt>
        <dd class="col-sm-10 text-light">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            <label class="text-light">Description</label>
        </dt>
        <dd class="col-sm-10 text-light">
            @Html.DisplayFor(model => model.description)
        </dd>
        <dt class = "col-sm-2">
            <label class="text-light">Type</label>
        </dt>
        <dd class="col-sm-10 text-light">
            @Html.DisplayFor(model => model.type)
        </dd>
        <dt class = "col-sm-2">
            <label class="text-light">Progress</label>
        </dt>
        <dd class="col-sm-10 text-light">
            @Html.DisplayFor(model => model.progress)
        </dd>
        <dt class="col-sm-2">
            <label class="text-light">Favorite</label>
        </dt>
        <dd class="col-sm-10 text-light">
            @Html.DisplayFor(model => model.favorite)
        </dd>
        <dt class="col-sm-2">
            <label class="text-light">Sprint Length</label>
        </dt>
        <dd class="col-sm-10 text-light">
            @Html.DisplayFor(model => model.sprint_length)
        </dd>
        <dt class="col-sm-2">
            <label class="text-light">Created</label>
        </dt>
        <dd class="col-sm-10 text-light">
            @Html.DisplayFor(model => model.created)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="text-light" asp-action="Index">Back to List</a>
    </form>
</div>

Artemis-Issue-Tracker/Views/Projects/Details.cshtml
@model Artemis_Issue_Tracker.Models.Project

@{
    ViewData["Title"] = "Details";
}

<h1 class="text-light">Details</h1>

<div>
    <h4 class="text-light">Project</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            <label class="text-light">Name</label>
        </dt>
        <dd class="col-sm-10 text-light">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class="col-sm-2">
            <label class="text-light">Description</label>
        </dt>
        <dd class="col-sm-10 text-light">
            @Html.DisplayFor(model => model.description)
        </dd>
        <dt class="col-sm-2">
            <label class="text-light">Type</label>
        </dt>
        <dd class="col-sm-10 text-light">
            @Html.DisplayFor(model => model.type)
        </dd>
        <dt class="col-sm-2">
            <label class="text-light">Progress</label>
        </dt>
        <dd class="col-sm-10 text-light">
            @Html.DisplayFor(model => model.progress)
        </dd>
        <dt class="col-sm-2">
            <label class="text-light">Favorite</label>
        </dt>
        <dd class="col-sm-10 text-light">
            @Html.DisplayFor(model => model.favorite)
        </dd>
        <dt class="col-sm-2">
            <label class="text-light">Sprint Length</label>
        </dt>
        <dd class="col-sm-10 text-light">
            @Html.DisplayFor(model => model.sprint_length)
        </dd>
        <dt class="col-sm-2">
            <label class="text-light">Created</label>
        </dt>
        <dd class="col-sm-10 text-light">
            @Html.DisplayFor(model => model.created)
        </dd>
    </dl>
</div>
<div>
    <a class="text-light" asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a class="text-light" asp-action="Index">Back to List</a>
</div>

Artemis-Issue-Tracker/Views/Projects/Index.cshtml
@model IEnumerable<Artemis_Issue_Tracker.Models.Project>
@using X.PagedList
@using X.PagedList.Mvc.Core
@using X.PagedList.Web.Common

@{
    ViewData["Title"] = "Index";

    var renderOptions = new PagedListRenderOptions
            {
                LiElementClasses = new List<string> { "page-item" },
                ContainerDivClasses = new List<string> { "pagination-container" },
                PageClasses = new List<string> { "page-link" },
                DisplayLinkToFirstPage = PagedListDisplayMode.IfNeeded,
                DisplayLinkToLastPage = PagedListDisplayMode.IfNeeded,
                DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
                DisplayLinkToNextPage = PagedListDisplayMode.Always,
                DisplayEllipsesWhenNotShowingAllPageNumbers = true,
                MaximumPageNumbersToDisplay = 10,
                LinkToFirstPageFormat = "&laquo;",
                LinkToPreviousPageFormat = "&lsaquo;",
                LinkToNextPageFormat = "&rsaquo;",
                LinkToLastPageFormat = "&raquo;",
                EllipsesFormat = "...",
            };
}
<div class="projects">
    <div class="view-header">
        <h1 class="view-title">Projects</h1>

        <div class="button-container">
            <a class="button-create" asp-action="Create">
                <svg class="button-icon" height="20" width="20" viewBox="0 0 20 20">
                    <g>
                        <circle cx="10" cy="10" r="9" stroke-width="2" fill="none" />
                        <line x1="5" y1="10" x2="15" y2="10" stroke-width="2"/>
                        <line x1="10" y1="5" x2="10" y2="15" stroke-width="2"/>
                    </g>
                </svg>
                <p>Create New</p>
            </a>
        </div>
    </div>

    <!-- Need to make this a dynamic search bar in furture sprint-->
    <div class="search-container">
        <form asp-controller="Projects" asp-action="Index">
            <input class="search-field" type="search" name="searchTerm" placeholder="Search Projects" oninput="document.querySelector('.search-icon').style.display = 'none', document.querySelector('.cancel-icon').style.display = 'initial'" />
        </form>

        <div class="search-icon">
            <span class="bi bi-search" aria-hidden="true" onclick="document.querySelector('.search-field').focus()"></span>
        </div>

        <div class="cancel-icon">
            <span class="bi bi-x" aria-hidden="true" onclick="document.querySelector('.search-icon').style.display = 'initial', document.querySelector('.cancel-icon').style.display = 'none', document.querySelector('.search-field').value = ''"></span>
        </div>
    </div>

    <table class="artemis-table">
        <thead>
            <tr>
                <th class="sortable-th">
                    <a class="@(ViewBag.CurrentSort == "title_ascend" ? "asc" : ViewBag.CurrentSort == "title_descend" ? "desc" : "")" 
                        href="@Url.Action("Index", new { sortOrder = ViewBag.TitleSort, currentFilter = ViewBag.CurrentFilter})">
                        <label>Project Name</label>

                        <svg class="sort-icon" width="14px" height="14px" viewBox="0 0 14 14">
                            <polygon class="sort-indicator" points="2,5 7,0 12,5"/>
                            <polygon class="sort-indicator" points="2,9 7,14 12,9"/>
                        </svg>
                    </a>
                </th>
                <th>
                    <label>Type</label>
                </th>
                <th class ="sortable-th">
                    <a class="@(ViewBag.CurrentSort == null ? "asc" : ViewBag.CurrentSort == "date_descend" ? "desc" : "")"
                        href="@Url.Action("Index", new { sortOrder = ViewBag.DateSort, currentFilter = ViewBag.CurrentFilter})">
                        <label>Creation Date</label>

                        <svg class="sort-icon" width="14px" height="14px" viewBox="0 0 14 14">
                            <polygon class="sort-indicator" points="2,5 7,0 12,5"/>
                            <polygon class="sort-indicator" points="2,9 7,14 12,9"/>
                        </svg>
                    </a>
                </th>
                <th class="sm-th"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model) {
                <tr>
                    <td>
                        <a asp-area="" asp-controller="Tasks" asp-action="Index">@Html.DisplayFor(modelItem => item.name)</a>
                    </td>
                    <td>
                        <label>@Html.DisplayFor(modelItem => item.type)</label>
                    </td>
                    <td>
                        <label>@Html.DisplayFor(modelItem => item.created, "DateTime")</label>
                    </td>
                    <td>
                        <div class="button-container">
                            <button class="button-threedot" id="project-settings-button @item.id" onclick="dropdownMenu.displayDropdown('project-settings-button @item.id', 'project-settings-menu', '@item.id')">
                                <svg width="24px" height="24px" viewBox="0 0 24 24">
                                    <g fill="currentColor" fill-rule="evenodd">
                                        <circle cx="5" cy="12" r="2"/>
                                        <circle cx="12" cy="12" r="2"/>
                                        <circle cx="19" cy="12" r="2"/>
                                    </g>
                                </svg>
                            </button>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @Html.PagedListPager(
        (IPagedList) Model, 
        page => Url.Action("Index", 
        new { 
            page, 
            sortOrder = ViewBag.CurrentSort, 
            currentFilter = ViewBag.CurrentFilter}),
            renderOptions
        )
</div>